name:                vTool
version:             0.1.0.0
github:              "githubuser/vTool"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vTool#readme>

dependencies:
- base >= 4.7 && < 5
- hlint
- apply-refact
- mtl
- containers
- exceptions
- bytestring
- text
- filepath
- directory
- ghc-lib
- ghc-lib-parser
- ghc-paths
- optparse-applicative
- optparse-generic
- hspec

library:
  source-dirs: src

executables:
  vTool:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vTool
